### ISSUE TITLE
Gutenberg Plugin Check

### ISSUE THREAD

**Issue by garysb** [editorblocks/editor-blocks-theme#2]
Is it still a requirement to check if the Wordpress installation has the Gutenberg plugin as it is now built into Wordpress? possibly check to ensure the Classic Editor plugin is not installed.

**Comment by DannyCooper** [comment]
Fixed in https://github.com/editorblocks/editor-blocks-theme/commit/6b1bfdad4e3beac7ef66d25cdc5efa4f625dc14f.

Thanks @garysb
